### ISSUE TITLE
The number of parameters that can be learned does not decrease

### ISSUE THREAD

**Issue by wt-suitors** [Rawwad-Alhejaili/Recursions-Are-All-You-Need#1]
Hello, I am very interested in your work, but you claim in the paper that "our proposed framework allows the network to reduce the number of learnable parameters by up to 75% while essentially maintaining its performance", yet the results of your open source code show The amount of parameters that can be learned is higher than Baseline. In addition, where is the recursion reflected in the paper? Thank you for taking the time to give your answer!

**Comment by Rawwad-Alhejaili** [comment]
Hi, thanks for showing interest in this work.

1. The number of learnable parameters is _mainly_ affected by the number of layers (the RFMU has a marginal impact to the number of parameters).  For example, COAST (the baseline) uses 20 layers and its number of learnable parameters is 1,122,024. On the other hand, R-COAST only has 5 layers which translates to having 281,674 parameters. The code `TRAIN_COAST.py` does return the number of learnable parameters of the network, so please double check that it returns the same numbers as reported here (I have just verified this on my end, but it doesn't hurt to double check). 
2. The number of recursions is reflected in the paper by the iterations per layer (IPL). Having IPL=1 means the network only performs a single iteration per layer. Since the output is NOT fed back to the input in this case, the network is NOT recursive. Therefore, for a network to be recursive, its IPL _must_ be greater than 1. In the tables, you could see that the baseline configuration always has IPL=1, meaning it has no recursions. The recursive configurations on the other hand have IPL=3 or IPL=4, meaning they perform multiple iterations on the same layer before passing to the next layer, which is recursions essentially.

Please let me know if this solved your issue, and please do not hesitate to ask if something needs clarification.

**Comment by wt-suitors** [comment]
Thank you very much for your reply despite your busy schedule, it really answered my doubts. I am a first-year graduate student who has just entered into in-depth network research. I am not familiar with this work and it has caused trouble for you. This is a great article and it has been an important inspiration for what I am currently doing. Thanks again for your reply!
